#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-UNIVERSAL-can
Version  : 1.20140328
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/C/CH/CHROMATIC/UNIVERSAL-can-1.20140328.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/C/CH/CHROMATIC/UNIVERSAL-can-1.20140328.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libu/libuniversal-can-perl/libuniversal-can-perl_1.20140328-1.debian.tar.xz
Summary  : 'work around buggy code calling UNIVERSAL::can() as a function'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-UNIVERSAL-can-man

%description
UNIVERSAL::can
--------------
This module attempts to work around people calling UNIVERSAL::can() as a
function, which it is not.

%package man
Summary: man components for the perl-UNIVERSAL-can package.
Group: Default

%description man
man components for the perl-UNIVERSAL-can package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n UNIVERSAL-can-1.20140328
mkdir -p %{_topdir}/BUILD/UNIVERSAL-can-1.20140328/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/UNIVERSAL-can-1.20140328/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/UNIVERSAL/can.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/UNIVERSAL::can.3
